name: Deploy to GitHub Pages on HTML change

on:
  workflow_dispatch:
  push:
    paths:
      - 'triton-architecture-diagram.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: '.'
